[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Daniel Porteous <daniel@dport.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aptos-sdk = "^0.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
