[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
aptos-sdk = { git = "https://github.com/aptos-labs/aptos-core", branch = "main" }

[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin" }
